# Generated by Django 2.2.2 on 2019-10-21 08:06

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191019_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='account',
            name='display_name',
            field=models.CharField(default='', max_length=30, verbose_name='display name'),
        ),
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.IntegerField(default=0, verbose_name='followers'),
        ),
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.IntegerField(default=0, verbose_name='following'),
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.upload_location),
        ),
        migrations.AddField(
            model_name='account',
            name='posts',
            field=models.IntegerField(default=0, verbose_name='posts'),
        ),
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.CharField(default='', max_length=30, verbose_name='website'),
        ),
    ]
