# Generated by Django 2.2.2 on 2019-10-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191021_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='website'),
        ),
    ]
