# Generated by Django 2.2.2 on 2019-10-26 14:12

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_account_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='static/default.png', upload_to=account.models.upload_location),
        ),
    ]
