# Generated by Django 2.2.2 on 2019-10-28 08:29

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20191026_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=account.models.upload_location),
        ),
    ]
