# Generated by Django 2.2.2 on 2019-11-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20191028_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follows',
            options={'verbose_name': 'Follow', 'verbose_name_plural': 'Follows'},
        ),
    ]
