# Generated by Django 2.2.2 on 2019-10-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypost',
            name='comments',
            field=models.CharField(default='0', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='storypost',
            name='likes',
            field=models.CharField(default='0', editable=False, max_length=5),
        ),
    ]
