# Generated by Django 2.2.2 on 2019-10-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20191020_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypost',
            name='tags',
            field=models.TextField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='storypost',
            name='title',
            field=models.TextField(default='iO1CWepT', editable=False, max_length=200),
        ),
    ]
