# Generated by Django 2.2.2 on 2019-10-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20191020_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypost',
            name='title',
            field=models.TextField(default='AEf6SK3C', editable=False, max_length=200),
        ),
    ]
