# Generated by Django 2.2.2 on 2019-10-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_auto_20191022_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypost',
            name='title',
            field=models.TextField(default='vgHNiHK2', editable=False, max_length=200),
        ),
    ]
