# Generated by Django 2.2.2 on 2019-10-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_auto_20191022_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypost',
            name='title',
            field=models.TextField(default='6UGXxGKg', editable=False, max_length=200),
        ),
    ]
