# Generated by Django 2.2.2 on 2019-10-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_auto_20191022_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypost',
            name='title',
            field=models.TextField(default='nBUy9Axq', editable=False, max_length=200),
        ),
    ]
