# Generated by Django 2.2.2 on 2019-10-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_auto_20191022_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypost',
            name='caption',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='storypost',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='storypost',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='storypost',
            name='tags',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='storypost',
            name='title',
            field=models.TextField(default='l0gSD9MF', editable=False, max_length=200),
        ),
    ]
