# Generated by Django 2.2.2 on 2019-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_auto_20191023_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypost',
            name='title',
            field=models.TextField(default='cjOVqMj2', editable=False, max_length=200),
        ),
    ]
