# Generated by Django 2.2.2 on 2019-10-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0016_auto_20191026_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypost',
            name='title',
            field=models.TextField(default='UT1HJLh1', editable=False, max_length=200),
        ),
    ]
