# Generated by Django 2.2.2 on 2019-10-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0017_auto_20191028_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypost',
            name='title',
            field=models.TextField(default='YEhBqWkT', editable=False, max_length=200),
        ),
    ]
