# Generated by Django 2.2.2 on 2019-10-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0018_auto_20191028_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypost',
            name='title',
            field=models.TextField(default='BCXlxAzx', editable=False, max_length=200),
        ),
    ]
