# Generated by Django 2.2.2 on 2019-11-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0019_auto_20191029_0706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storylikes',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='storypost',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Story Posts'},
        ),
        migrations.AlterField(
            model_name='storypost',
            name='caption',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='storypost',
            name='title',
            field=models.TextField(default='XYYe3tSh', editable=False, max_length=200),
        ),
    ]
